# Generated by Django 2.1.5 on 2020-01-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default=1, upload_to='photos')),
                ('primaryCategory', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('moving_method', models.CharField(max_length=200)),
                ('second_place', models.CharField(max_length=200)),
                ('third_place', models.CharField(max_length=200)),
                ('totaltime', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='photos')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category')),
            ],
        ),
    ]
