# Generated by Django 3.0 on 2019-12-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='orderitems',
        ),
    ]
