# Generated by Django 3.0 on 2019-12-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191224_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
