# Generated by Django 3.0 on 2019-12-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
