# Generated by Django 2.1.5 on 2020-01-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('primaryCategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(blank=True, upload_to='photos/')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('meeting_place', models.CharField(max_length=200)),
                ('moving_method', models.CharField(max_length=200)),
                ('second_place', models.CharField(max_length=200)),
                ('third_place', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(related_name='posts', to='app.Category')),
            ],
        ),
    ]
