# Generated by Django 2.1.5 on 2020-01-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
