# Generated by Django 2.1.5 on 2020-01-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200116_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='slug',
        ),
    ]
