# Generated by Django 2.1.5 on 2020-01-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_plan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_on',
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
