# Generated by Django 2.1.5 on 2020-01-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200117_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Category'),
        ),
    ]
