# Generated by Django 3.0 on 2019-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=20)),
                ('PhoneNumber', models.IntegerField()),
                ('work', models.CharField(max_length=20)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
